{% set name = "awkward" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcbba41e914f4d54f97410d95215ffeb154f541b9fb70f9108ce4730658a23ed

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  build:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy >=1.13.1

test:
  imports:
    - awkward

about:
  home: https://github.com/scikit-hep/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Manipulate arrays of complex data structures as easily as Numpy.'
  dev_url: https://github.com/scikit-hep/{{ name }}

extra:
  recipe-maintainers:
    - chrisburr
